######################## default configuration ####################
baseURL = "http://example.org/"
languageCode = "en-us"
title = "椒房餐厅"
theme = "restaurant-hugo"
summaryLength = "10"
paginate = 4

############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
URL = "css/bootstrap.min.css"
[[params.plugins.css]]
URL = "css/slick.css"
[[params.plugins.css]]
URL = "css/font-awesome.min.css"
[[params.plugins.css]]
URL = "css/animate.min.css"
[[params.plugins.css]]
URL = "css/venobox.css"
[[params.plugins.css]]
URL = "css/main.css"
[[params.plugins.css]]
URL = "css/responsive.css"

# JS Plugins
[[params.plugins.js]]
URL = "js/jquery.min.js"
[[params.plugins.js]]
URL = "js/bootstrap.min.js"
[[params.plugins.js]]
URL = "js/slick.min.js"
[[params.plugins.js]]
URL = "js/wow.min.js"
[[params.plugins.js]]
URL = "js/venobox.min.js"
[[params.plugins.js]]
URL = "js/main.js"

############################## navigation ###############################

[[menu.main]]
name = "主页"
URL = "hero-area"
weight = 1

[[menu.main]]
name = "关于椒房"
URL = "about-us"
weight = 2

[[menu.main]]
name = "菜品"
URL = "blog"
weight = 3

[[menu.main]]
name = "企业团餐"
URL = "price"
weight = 4

[[menu.main]]
name = "资讯"
URL = "subscribe"
weight = 5

[[menu.main]]
name = "联系我们"
URL = "contact-us"
weight = 6


#################### default parameters ################################
[params]
logo = "images/logo.png"
# meta data
author = "Themefisher"
description = "This is meta description"
# google analitycs ID
google_analitycs_id = "Your ID"
# mainSections
main_sections = ["post"]
# copyright
copyright = "Copyright &copy; 2020 Designed by [二木设计](https://www.2mui.com) & Developed by [二木设计](https://www.2mui.com)"

# Preloader
[params.preloader]
enable = false
preloader = "" # use .png , .svg or .gif format

################################### Footer ############################
[params.footer]
enable = true
contactInfoTitle = "联系 <span>方式</span> "
blogTitle = "最新 <span>菜品</span>"
galleryTitle = "照片 <span>流</span>"
socialTitle = "分享 <span>椒房</span>"

############################ footer contact item
[[params.footer.contactItem]]
title="手机号码"
icon = "fa fa-phone"
content = "15113801379"

[[params.footer.contactItem]]
title="餐厅地址"
icon = "fa fa-map-marker"
content = "关山大道软件园广场一楼椒房餐厅"

[[params.footer.contactItem]]
title="电子邮箱"
icon = "fa fa-envelope"
content = "930621523@qq.com"

######################### footer gallery
[[params.footer.gallery]]
image = "images/slider/slider-img-1.jpg"

[[params.footer.gallery]]
image = "images/slider/slider-img-2.jpg"

[[params.footer.gallery]]
image = "images/slider/slider-img-3.jpg"

[[params.footer.gallery]]
image = "images/slider/slider-img-4.jpg"

[[params.footer.gallery]]
image = "images/slider/slider-img-1.jpg"

[[params.footer.gallery]]
image = "images/slider/slider-img-2.jpg"

######################## Social Icon 
[[params.footer.socialLink]]
icon = "facebook"
link = "https://fb.com/themefisher"

[[params.footer.socialLink]]
icon = "twitter"
link = "https://fb.com/themefisher"

[[params.footer.socialLink]]
icon = "dribbble"
link = "https://fb.com/themefisher"

[[params.footer.socialLink]]
icon = "instagram"
link = "https://fb.com/themefisher"